sudo: false
dist: trusty

language: go
go:
  - '1.10.x'

go_import_path: gopkg.in/src-d/enry.v1

addons:
  apt:
    packages:
      - libonig-dev

env:
  global:
    - GO_VERSION='1.10.x'
    - ONIGURUMA=0

stages:
  - name: test
  - name: release
    if: tag IS present
  - name: publish
    if: tag IS present

jobs:
  include:
    - &golang-unit-tests
      name: 'golang unitTests'
      stage: test
      install:
        - gimme version
        - if [ "$ONIGURUMA" == "1" ]; then tags="$tags oniguruma"; fi; go get -v -t --tags "$tags" ./...
      script:
        - make test-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - <<: *golang-unit-tests
      name: 'golang unitTests, ONIGURUMA=1'
      env: ONIGURUMA=1

    - name: 'java unitTests'
      stage: test
      language: scala
      jdk: oraclejdk8
      install:
        - gimme version
        - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=$GO_VERSION bash)"
        - go version
        - go get -v gopkg.in/src-d/enry.v1/...
      before_script:
        - cd java
        - make
      script:
        - make test

    - name: 'linux packages'
      stage: release
      install:
        - go get -v -t ./...
      script: make packages
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true

    - name: 'linux shared lib'
      stage: release
      install:
        - go get -v -t ./...
      script: make linux-shared
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - ./.shared/linux-x86-64/libenry.so
        skip_cleanup: true
        on:
          tags: true

    - name: 'macOS shared lib'
      stage: release
      os: osx
      osx_image: xcode10.1
      sudo: true
      install:
        - go get -v -t ./...
      script: make darwin-shared
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: ./.shared/darwin/libenry.dylib
        skip_cleanup: true
        on:
          tags: true

    - name: 'java: publish to maven'
      stage: publish
      language: scala
      jdk: oraclejdk8
      install:
        - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=$GO_VERSION bash)"
        - go version
        - go get -v gopkg.in/src-d/enry.v1/...
      before_script:
        - cd java
        - make
        - curl -o ./shared/linux-x86-64/libenry.so -sfL "https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG/libenry.so" || travis_terminate 1
        - mkdir -p ./shared/darwin
        - curl -o ./shared/darwin/libenry.dylib -sfL "https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG/libenry.dylib" || travis_terminate 1
        - openssl aes-256-cbc -K $encrypted_a0e1c69dbbc7_key -iv $encrypted_a0e1c69dbbc7_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
      script:
        - make test # ensure the shared objects are functional
        - ./sbt publishLocal
        - ./sbt publishSigned
        - ./sbt sonatypeRelease
      before_deploy:
        - rm ./target/enry-java-*-javadoc.jar
        - rm ./target/enry-java-*-sources.jar
        - rm ./target/enry-java-*-tests.jar
        - rm ./target/enry-java-assembly-*.jar
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: ./target/enry-java*.jar
        skip_cleanup: true
        on:
          tags: true
