// Code generated by gopkg.in/src-d/enry.v1/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 1996fd8e095cd55c9d1702813a7df01bc5159c50

package data

// linguist's commit from which files were generated.
var LinguistCommit = "1996fd8e095cd55c9d1702813a7df01bc5159c50"
