// Code generated by gopkg.in/src-d/enry.v1/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: e761f9b013e5b61161481fcb898b59721ee40e3d

package data

// linguist's commit from which files were generated.
var LinguistCommit = "e761f9b013e5b61161481fcb898b59721ee40e3d"
